### ISSUE TITLE
RootNamespace prefix

### ISSUE THREAD

**Issue by BachiMjavanadze** [rsaz/csharp-snippet-productivity#11] opened 2022-04-25 18:34 UTC
It's very annoying when creating new project it adds SOLUTION_NAME prefix on folder name:

![image](https://user-images.githubusercontent.com/38082501/165152636-297c3696-3ec9-4201-a4d0-f45602dc9b2b.png)

Please give us chois add this prefix or not. Say, make option in settings:

`"csharp-snippet-productivity.AutoSolutionPrefixOnProjectName":  true/false`

**Comment by rsaz** [comment] 2022-04-28 07:18
Hi @BachiMjavanadze I could not reproduce this scenario. Can you paste or put here the steps that takes you to exact this issue? 
I created a project within solution and works normally without adding a solution prefix prior to the project name. Let me know.

**Comment by BachiMjavanadze** [comment] 2022-04-28 10:18
here is a video

https://youtu.be/B1odyPGAvHI

**Comment by BachiMjavanadze** [comment] 2022-04-28 10:22
Now I think it adds project path like a prefix

**Comment by rsaz** [comment] 2022-05-09 19:45
Hi @BachiMjavanadze this weekend I might look at this problem and if there is a bug as you demonstrated I will fix it and I will let you know on release. Thank you for pushing this. Regards

**Comment by rsaz** [comment] 2022-05-14 08:14
Hi @BachiMjavanadze thank you for the video, helped me to understand the problem. There is no issue on the extension, no one has ever complain about this particular issue you mentioned and there are two hypothesis possible: 1 they don't use MINGW from GIT bash and if they do they make sure that the command "code" (from vscode) is globally accessible. If you see in your video in the 0:45 second your bash is not able to access code command, so that it can't create the proper folder generating that weird behavior on adding project prefixing a path. Try to fix this, making code accessible on your mingw and let me know if the problem still persists. If does I can definitely propose a solution.

**Comment by BachiMjavanadze** [comment] 2022-05-14 12:05
I was using Portable VSCode and that was a problem, switch to normal one and promlem has gone (I don't want to write path manually for command "code").
Thanks!

Can you please add more project template? If it is not possible please add this one: "Minimal Web API". With Visual Studio IDE you can easily create it, you just need to uncheck this:

[https://i.imgur.com/AoIebaN.jpg](url)

.Net CLI command for "Minimal Web API":

`dotnet new webapi -minimal -o PROJECT_NAME`

should I open new issue for it?

Anyway, your extension is awesome and I'm gonna recommend it to everyone.

**Comment by rsaz** [comment] 2022-05-15 03:27
That's great news @BachiMjavanadze , I am glad that is working fine the extension for you, and thanks for recommending it.
I will be closing this issue. Please open a new issue for the new request, detailing what is being expected and I will be more than happy to add in the new 1.3.0 version.

**Closed by rsaz** 2022-05-15 03:27 UTC
